spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello-service
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 200m
            memory: 512Mi