spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello-service
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 512Mi