spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-service
        resources:
          limits:
            cpu: 450m
            memory: 768Mi
          requests:
            cpu: 200m
            memory: 512Mi